framework:
    cache:
        ***REMOVED*** Unique name of your app: used to compute stable namespaces for cache keys.
        ***REMOVED***prefix_seed: your_vendor_name/app_name

        ***REMOVED*** The "app" cache stores to the filesystem by default.
        ***REMOVED*** The data in this cache should persist between deploys.
        ***REMOVED*** Other options include:

        ***REMOVED*** Redis
        ***REMOVED***app: cache.adapter.redis
        ***REMOVED***default_redis_provider: redis://localhost

        ***REMOVED*** APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        ***REMOVED***app: cache.adapter.apcu

        ***REMOVED*** Namespaced pools use the above "app" backend by default
        ***REMOVED***pools:
            ***REMOVED***my.dedicated.cache: null
