doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    ***REMOVED*** namespace is arbitrary but should be different from App\Migrations
    ***REMOVED*** as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
