doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        ***REMOVED*** IMPORTANT: You MUST configure your db driver and server version,
        ***REMOVED*** either here or in the DATABASE_URL env var (see .env file)
        ***REMOVED***driver: 'mysql'
        ***REMOVED***server_version: '5.7'

        ***REMOVED*** Only needed for MySQL (ignored otherwise)
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
