framework:
    secret: '%env(APP_SECRET)%'
    ***REMOVED***csrf_protection: true
    ***REMOVED***http_method_override: true

    ***REMOVED*** Enables session support. Note that the session will ONLY be started if you read or write from it.
    ***REMOVED*** Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    ***REMOVED***esi: true
    ***REMOVED***fragments: true
    php_errors:
        log: true
