webpack_encore:
    ***REMOVED*** The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
    ***REMOVED*** If multiple builds are defined (as shown below), you can disable the default build:
    ***REMOVED*** output_path: false

    ***REMOVED*** if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    ***REMOVED*** crossorigin: 'anonymous'

    ***REMOVED*** preload all rendered script and link tags automatically via the http2 Link header
    ***REMOVED*** preload: true

    ***REMOVED*** Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    ***REMOVED*** strict_mode: false

    ***REMOVED*** if you have multiple builds:
    ***REMOVED*** builds:
        ***REMOVED*** pass "frontend" as the 3rg arg to the Twig functions
        ***REMOVED*** {{ encore_entry_script_tags('entry1', null, 'frontend') }}

        ***REMOVED*** frontend: '%kernel.project_dir%/public/frontend/build'

    ***REMOVED*** Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
    ***REMOVED*** Put in config/packages/prod/webpack_encore.yaml
    ***REMOVED*** cache: true
