webpack_encore:
    ***REMOVED*** The path where Encore is building the assets.
    ***REMOVED*** This should match Encore.setOutputPath() in webpack.config.js.
    output_path: '%kernel.project_dir%/public/build'
    ***REMOVED*** If multiple builds are defined (as shown below), you can disable the default build:
    ***REMOVED*** output_path: false

    ***REMOVED*** if using Encore.enableIntegrityHashes() specify the crossorigin attribute value (default: false, or use 'anonymous' or 'use-credentials')
    ***REMOVED*** crossorigin: 'anonymous'

    ***REMOVED*** Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes).
    ***REMOVED*** To enable caching for the production environment, creating a webpack_encore.yaml in the config/packages/prod directory with this value set to true
    ***REMOVED*** Available in version 1.2
    ***REMOVED***cache: false
