monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        ***REMOVED*** uncomment to get logging in your browser
        ***REMOVED*** you may have to allow bigger header sizes in your Web server configuration
        ***REMOVED***firephp:
        ***REMOVED***    type: firephp
        ***REMOVED***    level: info
        ***REMOVED***chromephp:
        ***REMOVED***    type: chromephp
        ***REMOVED***    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
